import { z } from "zod";
import { Publication } from "./publication";

const PubsByYear = z.array(
  z.object({
    year: z.string(),
    publications: z.array(Publication),
  }),
);

export const publicationsByYear = PubsByYear.parse([
  {
    year: "2025",
    publications: [
      {
        title:
          "Distillation Techniques for Network Reconstruction in Adaptive Systems",
        authors: ["Joost Weerheim"],
        date: "2025-6-27",
        year: "2025",
        type: "misc",
        tags: ["Computer Vision", "BSc"],
        id: "network-reconstruction-in-adaptive-systems-2025",
        file: "/publications/2025/Weerheim2025.pdf",
      },
    ],
  },
  {
    year: "2024",
    publications: [
      {
        title: "Dutch Nao Team - Technical Report",
        authors: [
          "Harold Ruiter",
          "Gijs de Jong",
          "Macha Meijer",
          "Marina Orozco González",
          "Mark Honkoop",
          "Julia Blaauboer",
          "Rick van der Veen",
          "Fyor Klein Gunnewiek",
          "Morris de Haan",
          "Fiona Nagelhout",
          "Joost Weerheim",
          "Stephan Visser",
          "Juell Sprott",
          "John Yao",
        ],
        date: "2024-12-30",
        year: "2024",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "techreport2024",
        file: "/publications/2024/DNT_Tech_Report_2024.pdf",
      },
      {
        title:
          "Position and Altitude of the Nao Camera Head from Two Points on the Soccer Field plus the Gravitational Direct",
        authors: ["Stijn Oomes", "Arnoud Visser"],
        date: "2024-7-3",
        year: "2024",
        type: "misc",
        tags: ["Localization"],
        id: "position-and-altitude-from-two-points-2024",
        file: "/publications/2024/position-and-altitude-from-two-points.pdf",
      },
      {
        title:
          "Introducing object detection to EKF SLAM on a Nao-robot football field",
        authors: ["Madelon Bernardy"],
        date: "2024-6-24",
        year: "2024",
        type: "misc",
        tags: ["Object detection"],
        id: "introducing-object-detection-to-ekf-slam-2024",
        file: "/publications/2024/introducing-object-detection-to-ekf-slam.pdf",
      },
      {
        title: "Team Description Paper Dutch Nao Team 2024",
        authors: [
          "Jakob Kaiser",
          "Ross Geurts",
          "Harold Ruiter",
          "Gijs de Jong",
          "Marina Orozco Gonzalez",
        ],
        date: "2024-2-13",
        year: "2024",
        type: "techreport",
        tags: ["Technical-Report", "Description"],
        id: "team_description_paper_2024",
        file: "/publications/2024/Qualification_Document_2024.pdf",
      },
      {
        title:
          "Optimising YOLOv8n using Maximum Class Separation and Data Augmentation for NAO robots",
        authors: [
          "Joost Weerheim",
          "Stephan Visser",
          "Kim Koomen",
          "Ross Geurts",
        ],
        date: "2024-2-6",
        year: "2024",
        type: "misc",
        tags: [
          "YOLO",
          "Maximum Class Separation ",
          "Data Augmentation",
          "Object detection",
        ],
        id: "optimizingYOLOv8n2024",
        file: "/publications/2024/Optimising_YOLOv8n_using_Maximum_Class_Separation_and_Data_Augmentation_for_NAO_robots.pdf",
      },
    ],
  },
  {
    year: "2023",
    publications: [
      {
        title: "Dutch Nao Team - Technical Report",
        authors: [
          "Gijs de Jong",
          "Harold Ruiter",
          "Derck W.E. Prinzhorn",
          "Jakob Kaiser",
          "Mark Honkoop",
          "Joost Weerheim",
          "Fyor Klein Gunnewiek",
          "Ross Geurts",
          "Dario Xavier Catarrinho",
          "Stephan Visser",
          "David Werkhoven",
          "Rick van der Veen",
          "Madelon Bernardy",
        ],
        date: "2023-12-31",
        year: "2023",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "techreport2023",
        file: "/publications/2023/DNT_Tech_Report_2023.pdf",
      },
      {
        title:
          "Using Neural Factorization of Shape and Reflectance for Ball Detection",
        authors: [
          "Xavier Monté",
          "Joey van der Kaaij",
          "Rogier van der Weerd",
          "Arnoud Visser",
        ],
        date: "2023-7-1",
        year: "2023",
        type: "misc",
        tags: ["Reflectance estimation", "View synthesis", "Object detection"],
        id: "xavieretal2023",
        file: "/publications/2023/Neural_Factorization_of_Shape_and_Reflectance_of_a_Soccer_Ball_Under_an_Unknown_Illumination.pdf",
      },
      {
        title:
          "Predicting a robot's position on a football field by training a machine learning algorithm on artificially generated data",
        authors: ["Lex Bolt"],
        date: "2023-06-23",
        year: "2023",
        type: "misc",
        tags: ["BSc", "Localization", "Unity"],
        id: "Bolt2023",
        file: "/publications/2023/Bachelorthesis_Lex_Bolt.pdf",
      },
      {
        title:
          "Exploring the Effectiveness of Object Detection Training in Virtual Environments",
        authors: ["Tobie Werner"],
        date: "2023-6-23",
        year: "2023",
        type: "misc",
        tags: ["BSc", "YOLO", "Unity"],
        id: "Werner2023",
        file: "/publications/2023/Bachelor_Thesis_Tobie_Werner.pdf",
      },
      {
        title: "Team Qualification Document for RoboCup 2023",
        authors: [
          "Wike Duivenvoorden",
          "Gijs de Jong",
          "Harold Ruiter",
          "Lex Bolt",
          "Derck Prinzhorn",
          "Fyor Klein Gunnewiek",
          "Lasse van Iterson",
          "Hidde Lekanne gezegd Deprez",
          "Thomas Brouwers",
          "Arnoud Visser",
        ],
        date: "2023-2-13",
        year: "2023",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "Duivenvoorden2023",
        file: "/publications/2023/TeamQualificationDocument2023.pdf",
      },
      {
        title:
          "Neural Factorization of Shape and Reflectance of a football Under an Unknown Illumination",
        authors: ["Xavier Monté"],
        date: "2023-02-03",
        year: "2023",
        type: "misc",
        tags: ["BSc", "NERF"],
        id: "monte2022",
        file: "https://staff.fnwi.uva.nl/a.visser/education/bachelorAI/Monte_NERF_of_a_football_under_unknown_illumination.pdf",
      },
    ],
  },
  {
    year: "2022",
    publications: [
      {
        title: "Dutch Nao Team - Technical Report",
        authors: [
          "Lex Bolt",
          "Fyor Klein Gunnewiek",
          "Hidde Lekanne gezegd Deprez",
          "Lasse van Iterson",
          "Derck Prinzhorn",
        ],
        date: "2022-12-26",
        year: "2022",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "Bolt2022",
        file: "/publications/2022/Bolt2022.pdf",
      },
      {
        title: "Team Qualification Document for RoboCup 2022 Bangkok, Thailand",
        authors: [
          "Wike Duivenvoorden",
          "Hidde Lekanne gezegd Deprez",
          "Thomas Wiggers",
          "Jakob Kaizer",
          "Rogier van der Weerd",
          "Pim Heeman",
          "Arnoud Visser",
        ],
        date: "2022-02-14",
        year: "2022",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "Duivenvoorden2022",
        file: "/publications/2022/Duivenvoorden2022.pdf",
      },
      {
        title: "Dutch Nao Team - Technical Report",
        authors: [
          "Jakob Kaiser",
          "Hidde Lekanne gezegd Deprez",
          "Wike Duivenvoorden",
          "Pim Heeman",
          "Rogier van der Weerd",
          "Thomas Wiggers",
        ],
        date: "2022-01-16",
        year: "2022",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "Kaiser2021",
        file: "/publications/2022/Kaiser2021.pdf",
      },
    ],
  },
  {
    year: "2021",
    publications: [
      {
        title: "Dutch Nao Team - Technical Report",
        authors: [
          "Pim Heeman",
          "Thomas Wiggers",
          "Hidde Lekanne gezegd Deprez",
          "Wouter Zwerink",
        ],
        date: "2021-01-01",
        year: "2021",
        type: "techreport",
        tags: ["Technical-Report"],
        id: "Heeman2021",
        file: "/publications/2021/Heeman2021.pdf",
      },
      {
        title:
          "Project AI: Real-time object detection and avoidance for autonomous Nao Robots performing in the Standard Platform League",
        authors: ["Rogier van der Weerd"],
        date: "2021-07-13",
        year: "2021",
        type: "techreport",
        tags: ["Msc", "Object-Detection", "YOLO"],
        id: "Weerd2021",
        file: "/publications/2021/Weerd2021.pdf",
      },
    ],
  },
]);
